tinylibs/tinypool

src/index.ts
This only happens on massive concurrency. Unblocks https://github.com/vueuse/vueuse/pull/1092 and https://github.com/vitest-dev/vitest/pull/295
=> fix(isolate): do not trigger avaliable event when isolated

src/common.ts, src/index.ts
In TS 4.4 or 4.5, they change the `catch (e: unknown)` from `Error` to `unknown` as throwing a none `Error` is also valid in JS.
This PR makes the typechecker stop complaining about the error.
=> fix(types): change error type to unknown

src/worker.ts
CJS workers need to have their `.default` export unwrapped
=> fix: use `.default` of worker module if it exists

.github/workflows/nodejs.yml, README.md, pnpm-lock.yaml, src/common.ts, src/index.ts, src/worker.ts, test/fixtures/workerId.js, test/simple.test.ts
It can be imported from `tinypool` as `workerId` in the worker when running!
=> feat: workerId

src/physicalCpuCount.ts
- This pr is created as a result of  [discussion](https://github.com/tinylibs/tinypool/discussions/33#discussioncomment-3081868). We found the max thread count when equal to the number of physical cores is the best way, but not before.
- We use the command `cat /proc/cpuinfo | grep "physical id" | sort |uniq | wc -l` to get the physical CPU number and use the command `cat /proc/cpuinfo | grep "core id" | sort | uniq | wc -l` to get physical CPU core number in each CPU. Finally, we can get the physical CPU cores number by multiplying these two values together.
=> fix: optimize the algorithm for cpu count calculation in the linux

README.md, src/physicalCpuCount.ts
- os.platform() will never be equal to 'windows', so it is a useless condition in the changed file.
- OS API Document: http://nodejs.cn/api-v16/os.html#osplatform
- delete this condition
=> fix: delete useless plafrom condition

README.md
It should be safe to recommend this as we target Node 14 or newer, and this was added in Node 14.8. Worst case, the user gets an error and learns to wrap it in a function as needed.
=> Use top-level await in example

src/index.ts
Reproduction:
pool.mjs:
```
import Tinypool from 'tinypool';
const pool = new Tinypool({
filename: new URL('./worker-id.mjs', import.meta.url).href,
});
pool.run();
pool.run();
pool.run();
pool.run();
pool.run();
```
worker-id.mjs
```
import { workerId } from 'tinypool';
export default function () {
console.log('workerId', workerId);
}
```
`node pool.mjs`:
```
% node pool.mjs
workerId undefined
workerId undefined
workerId undefined
workerId 1
workerId undefined
```
=> fix workerIds when maxThreads is undefined at passed options.

package.json, src/index.ts, test/fixtures/sleep.js, test/pool-destroy.test.ts, test/simple.test.ts, test/uncaught-exception-from-handler.test.ts
Resolves #43
Resolves #42 
@overlookmotel I did the maximumWorkers trick, but I do not have any reproduction for the halting issue, I'd like to see that so I'd write a proper test case for that.
=> fix: destroy issue and use maximum workers

README.md
There is no need to use the `path` module since you are using `new URL` and `import.meta.url` to resolve the file location instead.
=> chore: remove unnecessary import of 'path'

benchmark/fixtures/add.mjs, benchmark/fixtures/wrap-add.mjs, benchmark/isolate-benchmark.mjs, benchmark/simple-benchmark.mjs
- Fixes broken `benchmark/simple-benchmark.js` by converting it to ESM and changing `pool`'s method
- Adds new benchmark for testing whether Tinypool does something expensive when creating and terminating workers.
=> chore: add benchmark for worker isolation

README.md, src/common.ts, src/index.ts, test/task-queue.test.ts
- Fixes #52 
Here is the same test case with `signal` usage to demonstrate the issue clearly:
<details>
```ts
import EventEmitter from 'events'
test('queued tasks can be aborted', async () => {
const pool = new Tinypool({
filename: resolve(__dirname, 'fixtures/sleep.js'),
minThreads: 0,
maxThreads: 1,
})
const signal = new EventEmitter()
const time = 500
const promises = []
let finishedTasks = 0
let cancelledTasks = 0
for (const _ of Array(10).fill(0)) {
const promise = pool
.run({ time }, { signal })
.then(() => {
finishedTasks++
})
.catch((error) => {
if (error.message !== 'The task has been aborted') {
throw error
}
cancelledTasks++
})
promises.push(promise)
}
// Wait for task to start
await new Promise((resolve) => setTimeout(resolve, time / 2))
expect(pool.queueSize).toBe(9)
// One …
```
=> feat: `pool.cancelPendingTasks` method

src/index.ts, test/simple.test.ts
I noticed that when using `isolateWorkers: true`, `minThreads` is not respected correctly.
After every worker run the worker is terminated, but no new workers are started unless the task-queue is bigger than the worker count.
This fix ensures that after a worker is terminated we ensure that we have the minimum amount of workers running.
Let me know what you think about this. :)
=> fix: ensure that `minThreads` is respected when using `isolateWorkers`

README.md, src/common.ts, src/index.ts, src/worker.ts, test/fixtures/leak-memory.js, test/resource-limits.test.ts
- Closes #56
The implementation is highly inspired by `jest-worker`'s `idleMemoryLimit` option. 
Each worker reports their `process.memoryUsage().heapUsed` to main thread when they have finished the current task. Main thread compares this limit to pool's new memory limit option and decides whether worker should be terminated and replaced with new one.
=> feat: add `maxMemoryLimitBeforeRecycle` options

src/index.ts, test/resource-limits.test.ts
- Fixes https://github.com/tinylibs/tinypool/pull/58#issuecomment-1611266670
- Tested with Vitest's VM isolation PR. Crashes are now gone.
=> fix: dont mark recycled workers as available

README.md, src/index.ts, test/isolation.test.ts
=> feat: `pool.recycleWorkers()` method

README.md, package.json, src/common.ts, src/entry/process.ts, src/entry/utils.ts, src/entry/worker.ts, src/index.ts, src/runtime/process-worker.ts, src/runtime/thread-worker.ts, test/fixtures/child_process-communication.mjs, test/fixtures/leak-memory.js, test/isolation.test.ts, test/resource-limits.test.ts, test/runtime.test.ts, tsup.config.ts
- Closes #64 
&nbsp;
- No semver breaking changes
- Adds new internal common interface `TinypoolWorker`
- Moves existing `node:worker_threads` worker to `runtime/thread-worker.ts` - backwards compatible
- Adds new `runtime` option for pool constructor
- Creates new `TinypoolWorker` which runs on `node:child_process`, `runtime/process-worker.ts`. This is used when `runtime: 'child_process'` pool option is used.
- Adds new `channel` option for `pool.run()` method. This is used to pass callback for **main thread/process <-> worker** communication. This option is not supported by `ThreadWorker`.
- Adds new `runtime` option for `pool.recycleWorkers`. This can be used to recycle current workers and change the runtime of next set of workers.
&nbsp;
=> feat: support `runtime` option

src/runtime/process-worker.ts, src/runtime/thread-worker.ts
=> refactor: modify worker file path to satisfy the dependency analysis

src/index.ts, test/runtime.test.ts
Idle workers are not recycled when `runtime` changes and `isolateWorkers: true` option is used.
https://github.com/tinylibs/tinypool/blob/999778ed8acccf18303760558f807f0e208c8b3b/src/index.ts#L1074-L1081
This bug was introduced in https://github.com/tinylibs/tinypool/pull/65/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R1073 where `runtime` changing during `recycleWorkers` was introduced.
=> fix: `recycleWorkers` to destroy idle workers when `runtime` changes

src/runtime/process-worker.ts, test/simple.test.ts
Fixed: https://github.com/tinylibs/tinypool/issues/78
add pass argv
https://github.com/nodejs/node/blob/main/lib/child_process.js#L158
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/child_process.d.ts#L1391
add to parameters `options.argv`
```js
this.process = fork(
fileURLToPath(import.meta.url + '/../entry/process.js'),
options.argv,
options
)
```
=> fix: pass argv to child_process

src/common.ts, src/entry/process.ts, src/runtime/process-worker.ts, test/runtime.test.ts
First attempt at using the correct `threadId`/`workerId` for the worker when in `child_process` mode.
- Set worker data as required in init options as it seems to be always defined.
- Pass internal (correct) tinypool workerId down to fork with `process.env`
- Set correct fork state `process.__tinypool_state__.workerId` from the env variable
=> fix: set correct `workerId` in `runtime: 'child_process'`

src/entry/process.ts, src/entry/worker.ts, test/globals.test.ts
- Fixes https://github.com/vitest-dev/vitest/issues/5390
=> fix: prevent hang when process is overwritten

src/index.ts, test/pool-destroy.test.ts
This issue came up while looking into https://github.com/vitest-dev/vitest/pull/5544.
Tinypool's async resources show up in [Vitest's `hanging-process` reporter](https://vitest.dev/guide/reporters.html#hanging-process-reporter).
https://github.com/tinylibs/tinypool/blob/f86e82927371b54ba26577d818b86393ccf902c2/src/EventEmitterAsyncResource.ts#L24
```
RUN  v1.5.0 /Users/x/vitest/test/cli/fixtures/project
✓ |space_1| base.test.ts  (1 test) 2ms
Test Files  1 passed (1)
Tests  1 passed (1)
Start at  21:40:23
Duration  197ms (transform 17ms, setup 0ms, collect 12ms, tests 2ms, environment 0ms, prepare 66ms)
There are 12 handle(s) keeping the process running
node:internal/async_hooks:202                                                                             
node:internal/async_hooks:505 …
```
=> fix: `pool.destroy` to clean up async resources

src/entry/process.ts, test/fixtures/nested-pool.mjs, test/termination.test.ts
=> fix: prevent new workers from writing to closed pool

package.json
Add `./package.json` to `exports` for package locating.
When bundling a node library, one may need to copy the `dist/entry` directory into output directory (because it is not directly referenced). It is useful to have a `package.json` export when one uses build script like this:
```ts
require.resolve('tinypool/package.json')
```
It is also common practice for popular packages such as vite.
https://github.com/vitejs/vite/blob/1025bb6d8f21c0cb9fe72405d42e0f91bb3f1d8e/packages/vite/package.json#L43
=> chore: add "./package.json" to exports

README.md
It seems Piscina has since reduces its bundle size from 6MB to ~777KB as reported by [packagephobia](https://packagephobia.com/result?p=piscina)
=> docs: update Piscina install size comparison

.github/workflows/publish.yml
https://github.blog/changelog/2025-07-31-npm-trusted-publishing-with-oidc-is-generally-available/
=> ci: setup publish workflow
